function value = is_valid_density_band(p_min, p_max, dx)

value = is_positive_scalar(dx) ...
    && isreal(p_min) && isvector(p_min) ...
    && isreal(p_max) && isvector(p_max) ...
    && length(p_min) == length(p_max) ...
    && max(sum(p_min)*dx) <= 1 ...
    && min(sum(p_max)*dx) >= 1 ...
    && all(p_min >= 0) ...
    && all(p_min <= p_max);
